version: '2'

services:
    reverseproxy:
        image: reverseproxy
        container_name: nginx-rvrsproxy
        ports:
            - 80:80
        restart: always

    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        container_name: nginx-frontend
        restart: always
